FROM python:3.10

RUN apt-get update -y \
    && apt-get clean -y \
    && apt-get autoremove -y \
    && rm -rfd /tmp/* /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt && \
    rm -rdf /tmp/*

WORKDIR /srv/app/
COPY . .
ENV PYTHONPYCACHEPREFIX=/tmp
