FROM python:3.10

RUN apt-get update -y \
    && apt-get clean -y \
    && apt-get autoremove -y \
    && rm -rfd /tmp/* /var/lib/apt/lists/*

WORKDIR /srv/app/
COPY src .
RUN python3 -m pip install --no-cache-dir .
ENV PYTHONPYCACHEPREFIX=/tmp
