BASEPATH = "/api/v1"
BASEURL = "http://localhost:8000" + BASEPATH

TOKEN_PATH = "/users/login"
TOKEN_URL = BASEPATH + TOKEN_PATH

REGISTER_PATH = "/users/"
REGISTER_URL = BASEURL + REGISTER_PATH

LOGIN_PATH = "/users/login"
LOGIN_URL = BASEURL + LOGIN_PATH

PLANS_PATH = "/plans/"
PLAN_URL = BASEURL + PLANS_PATH

ROUTINES_PATH = "/routines/"
ROUTINES_URL = BASEURL + ROUTINES_PATH

USERNAME = "foo"
PASSWORD = "bar"
EMAIL = "foo@bar.com"
