BASEPATH = "/api/v1"
BASEURL = "http://localhost:8000"

TOKEN_PATH = BASEPATH + "/users/login"
TOKEN_URL = BASEURL + TOKEN_PATH

REGISTER_PATH = BASEPATH + "/users/"
REGISTER_URL = BASEURL + REGISTER_PATH

LOGIN_PATH = BASEPATH + "/users/login"
LOGIN_URL = BASEURL + LOGIN_PATH

PLANS_PATH = BASEPATH + "/plans/"
PLAN_URL = BASEURL + PLANS_PATH

ROUTINES_PATH = BASEPATH + "/routines/"
ROUTINES_URL = BASEURL + ROUTINES_PATH

USERNAME = "foo"
PASSWORD = "bar"
EMAIL = "foo@bar.com"
