// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { PostUsersData, PostUsersResponse, PostUsersError, PostUsersLoginData, PostUsersLoginResponse, PostUsersLoginError, GetUsersMeData, GetUsersMeResponse, GetUsersMeError, GetPlansData, GetPlansResponse, PostPlansData, PostPlansResponse, PostPlansError, GetPlansByIdData, GetPlansByIdResponse, GetPlansByIdError, PatchPlansByIdData, PatchPlansByIdResponse, PatchPlansByIdError, GetRoutinesData, GetRoutinesResponse, GetRoutinesError, PostRoutinesData, PostRoutinesResponse, PostRoutinesError, GetRoutinesByIdData, GetRoutinesByIdResponse, GetRoutinesByIdError, PatchRoutinesByIdData, PatchRoutinesByIdResponse, PatchRoutinesByIdError, GetExercisesData, GetExercisesResponse, GetExercisesError, PostExercisesData, PostExercisesResponse, PostExercisesError, GetExercisesByExerciseIdData, GetExercisesByExerciseIdResponse, GetExercisesByExerciseIdError, PatchExercisesByExerciseIdData, PatchExercisesByExerciseIdResponse, PatchExercisesByExerciseIdError, GetWorkoutsData, GetWorkoutsResponse, PostWorkoutsData, PostWorkoutsResponse, PostWorkoutsError, PatchWorkoutsByWorkoutIdData, PatchWorkoutsByWorkoutIdResponse, PatchWorkoutsByWorkoutIdError, DeleteRoutinesExercisesData, DeleteRoutinesExercisesResponse, DeleteRoutinesExercisesError, PostRoutinesExercisesData, PostRoutinesExercisesResponse, PostRoutinesExercisesError, DeleteWorkoutExercisesData, DeleteWorkoutExercisesResponse, DeleteWorkoutExercisesError, GetWorkoutExercisesData, GetWorkoutExercisesResponse, GetWorkoutExercisesError, PostWorkoutExercisesData, PostWorkoutExercisesResponse, PostWorkoutExercisesError, DeletePlansRoutinesData, DeletePlansRoutinesResponse, DeletePlansRoutinesError, GetPlansRoutinesData, GetPlansRoutinesResponse, GetPlansRoutinesError, PostPlansRoutinesData, PostPlansRoutinesResponse, PostPlansRoutinesError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export class DefaultService {
    /**
     * Register
     */
    public static postUsers<ThrowOnError extends boolean = false>(options: Options<PostUsersData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostUsersResponse, PostUsersError, ThrowOnError>({
            url: '/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Login
     */
    public static postUsersLogin<ThrowOnError extends boolean = false>(options: Options<PostUsersLoginData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostUsersLoginResponse, PostUsersLoginError, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/users/login',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Current User
     */
    public static getUsersMe<ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUsersMeResponse, GetUsersMeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/me',
            ...options
        });
    }
    
    /**
     * Read Workout Plans
     */
    public static getPlans<ThrowOnError extends boolean = false>(options?: Options<GetPlansData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPlansResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans/',
            ...options
        });
    }
    
    /**
     * Create Workout Plan
     */
    public static postPlans<ThrowOnError extends boolean = false>(options: Options<PostPlansData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostPlansResponse, PostPlansError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Workout Plan
     */
    public static getPlansById<ThrowOnError extends boolean = false>(options: Options<GetPlansByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetPlansByIdResponse, GetPlansByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans/{id}',
            ...options
        });
    }
    
    /**
     * Update Workout Plan
     */
    public static patchPlansById<ThrowOnError extends boolean = false>(options: Options<PatchPlansByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<PatchPlansByIdResponse, PatchPlansByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Routines
     */
    public static getRoutines<ThrowOnError extends boolean = false>(options?: Options<GetRoutinesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetRoutinesResponse, GetRoutinesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines/',
            ...options
        });
    }
    
    /**
     * Create Routine
     */
    public static postRoutines<ThrowOnError extends boolean = false>(options: Options<PostRoutinesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostRoutinesResponse, PostRoutinesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Routine
     */
    public static getRoutinesById<ThrowOnError extends boolean = false>(options: Options<GetRoutinesByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetRoutinesByIdResponse, GetRoutinesByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines/{id}',
            ...options
        });
    }
    
    /**
     * Update Routine
     */
    public static patchRoutinesById<ThrowOnError extends boolean = false>(options: Options<PatchRoutinesByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<PatchRoutinesByIdResponse, PatchRoutinesByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Exercises
     */
    public static getExercises<ThrowOnError extends boolean = false>(options?: Options<GetExercisesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetExercisesResponse, GetExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/exercises/',
            ...options
        });
    }
    
    /**
     * Create Exercise
     */
    public static postExercises<ThrowOnError extends boolean = false>(options: Options<PostExercisesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostExercisesResponse, PostExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/exercises/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Exercise
     */
    public static getExercisesByExerciseId<ThrowOnError extends boolean = false>(options: Options<GetExercisesByExerciseIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetExercisesByExerciseIdResponse, GetExercisesByExerciseIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/exercises/{exercise_id}',
            ...options
        });
    }
    
    /**
     * Update Exercise
     */
    public static patchExercisesByExerciseId<ThrowOnError extends boolean = false>(options: Options<PatchExercisesByExerciseIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<PatchExercisesByExerciseIdResponse, PatchExercisesByExerciseIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/exercises/{exercise_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Read Workouts
     */
    public static getWorkouts<ThrowOnError extends boolean = false>(options?: Options<GetWorkoutsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetWorkoutsResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workouts/',
            ...options
        });
    }
    
    /**
     * Create Workout
     */
    public static postWorkouts<ThrowOnError extends boolean = false>(options: Options<PostWorkoutsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostWorkoutsResponse, PostWorkoutsError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workouts/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Update Workout
     */
    public static patchWorkoutsByWorkoutId<ThrowOnError extends boolean = false>(options: Options<PatchWorkoutsByWorkoutIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<PatchWorkoutsByWorkoutIdResponse, PatchWorkoutsByWorkoutIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workouts/{workout_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete Exercise From Routine
     */
    public static deleteRoutinesExercises<ThrowOnError extends boolean = false>(options: Options<DeleteRoutinesExercisesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteRoutinesExercisesResponse, DeleteRoutinesExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines-exercises/',
            ...options
        });
    }
    
    /**
     * Add Exercise To Routine
     */
    public static postRoutinesExercises<ThrowOnError extends boolean = false>(options: Options<PostRoutinesExercisesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostRoutinesExercisesResponse, PostRoutinesExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/routines-exercises/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete Exercise From Routine
     */
    public static deleteWorkoutExercises<ThrowOnError extends boolean = false>(options: Options<DeleteWorkoutExercisesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteWorkoutExercisesResponse, DeleteWorkoutExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workout-exercises/',
            ...options
        });
    }
    
    /**
     * Read Routine Exercise Pairs
     */
    public static getWorkoutExercises<ThrowOnError extends boolean = false>(options?: Options<GetWorkoutExercisesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetWorkoutExercisesResponse, GetWorkoutExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workout-exercises/',
            ...options
        });
    }
    
    /**
     * Add Workout Stats
     */
    public static postWorkoutExercises<ThrowOnError extends boolean = false>(options: Options<PostWorkoutExercisesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostWorkoutExercisesResponse, PostWorkoutExercisesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/workout-exercises/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete Routine From Plan
     */
    public static deletePlansRoutines<ThrowOnError extends boolean = false>(options: Options<DeletePlansRoutinesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeletePlansRoutinesResponse, DeletePlansRoutinesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans-routines/',
            ...options
        });
    }
    
    /**
     * Read Plan Routine Pairs
     */
    public static getPlansRoutines<ThrowOnError extends boolean = false>(options?: Options<GetPlansRoutinesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPlansRoutinesResponse, GetPlansRoutinesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans-routines/',
            ...options
        });
    }
    
    /**
     * Add Routine To Plan
     */
    public static postPlansRoutines<ThrowOnError extends boolean = false>(options: Options<PostPlansRoutinesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostPlansRoutinesResponse, PostPlansRoutinesError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/plans-routines/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}