// This file is auto-generated by @hey-api/openapi-ts

export type BodyLoginUsersLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type ExerciseCreate = {
    name: string;
    description?: string | null;
};

export type ExerciseRead = {
    name: string;
    description?: string | null;
    id: number;
};

export type ExerciseUpdate = {
    name: string;
    description?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    msg: string;
};

export type PlanCreate = {
    name?: string | null;
    start_date?: string | null;
    end_date?: string | null;
};

export type PlanRead = {
    name?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    id: number;
};

export type PlanRoutineLink = {
    plan_id?: number | null;
    routine_id?: number | null;
};

export type PlanUpdate = {
    name?: string | null;
    start_date?: string | null;
    end_date?: string | null;
};

export type RoutineCreate = {
    name?: string | null;
};

export type RoutineExerciseLink = {
    routine_id?: number | null;
    exercise_id?: number | null;
};

export type RoutineRead = {
    name?: string | null;
    id: number;
};

export type RoutineUpdate = {
    name?: string | null;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type UserCreate = {
    username: string;
    email: string;
    /**
     * Only alphanumeric characters and !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ are allowed in this field
     */
    password: string;
};

export type UserRead = {
    username: string;
    email: string;
    id: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type Workout = {
    date: string;
    id?: number | null;
    routine_id: number;
};

export type WorkoutCreate = {
    date: string;
    routine_id: number;
};

export type WorkoutExerciseLink = {
    workout_id: number;
    exercise_id: number;
    sets?: number | null;
    reps?: number | null;
    seconds_of_rest?: number | null;
    weight?: number | null;
};

export type WorkoutRead = {
    date: string;
    id: number;
    routine_id: number;
};

export type WorkoutUpdate = {
    date: string;
};

export type PostUsersData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type PostUsersErrors = {
    /**
     * Conflict
     */
    409: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type PostUsersLoginData = {
    body: BodyLoginUsersLoginPost;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type PostUsersLoginErrors = {
    /**
     * Bad Request
     */
    400: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersLoginError = PostUsersLoginErrors[keyof PostUsersLoginErrors];

export type PostUsersLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type PostUsersLoginResponse = PostUsersLoginResponses[keyof PostUsersLoginResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Not Found
     */
    404: Message;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type GetPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plans/';
};

export type GetPlansResponses = {
    /**
     * Successful Response
     */
    200: Array<PlanRead>;
};

export type GetPlansResponse = GetPlansResponses[keyof GetPlansResponses];

export type PostPlansData = {
    body: PlanCreate;
    path?: never;
    query?: never;
    url: '/plans/';
};

export type PostPlansErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPlansError = PostPlansErrors[keyof PostPlansErrors];

export type PostPlansResponses = {
    /**
     * Successful Response
     */
    201: PlanRead;
};

export type PostPlansResponse = PostPlansResponses[keyof PostPlansResponses];

export type GetPlansByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/plans/{id}';
};

export type GetPlansByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlansByIdError = GetPlansByIdErrors[keyof GetPlansByIdErrors];

export type GetPlansByIdResponses = {
    /**
     * Successful Response
     */
    200: PlanRead;
};

export type GetPlansByIdResponse = GetPlansByIdResponses[keyof GetPlansByIdResponses];

export type PatchPlansByIdData = {
    body: PlanUpdate;
    path: {
        id: number;
    };
    query?: never;
    url: '/plans/{id}';
};

export type PatchPlansByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchPlansByIdError = PatchPlansByIdErrors[keyof PatchPlansByIdErrors];

export type PatchPlansByIdResponses = {
    /**
     * Successful Response
     */
    200: PlanRead;
};

export type PatchPlansByIdResponse = PatchPlansByIdResponses[keyof PatchPlansByIdResponses];

export type GetRoutinesData = {
    body?: never;
    path?: never;
    query?: {
        plan_id?: number | null;
    };
    url: '/routines/';
};

export type GetRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoutinesError = GetRoutinesErrors[keyof GetRoutinesErrors];

export type GetRoutinesResponses = {
    /**
     * Successful Response
     */
    200: Array<RoutineRead>;
};

export type GetRoutinesResponse = GetRoutinesResponses[keyof GetRoutinesResponses];

export type PostRoutinesData = {
    body: RoutineCreate;
    path?: never;
    query?: never;
    url: '/routines/';
};

export type PostRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRoutinesError = PostRoutinesErrors[keyof PostRoutinesErrors];

export type PostRoutinesResponses = {
    /**
     * Successful Response
     */
    201: RoutineRead;
};

export type PostRoutinesResponse = PostRoutinesResponses[keyof PostRoutinesResponses];

export type GetRoutinesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/routines/{id}';
};

export type GetRoutinesByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoutinesByIdError = GetRoutinesByIdErrors[keyof GetRoutinesByIdErrors];

export type GetRoutinesByIdResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type GetRoutinesByIdResponse = GetRoutinesByIdResponses[keyof GetRoutinesByIdResponses];

export type PatchRoutinesByIdData = {
    body: RoutineUpdate;
    path: {
        id: number;
    };
    query?: never;
    url: '/routines/{id}';
};

export type PatchRoutinesByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchRoutinesByIdError = PatchRoutinesByIdErrors[keyof PatchRoutinesByIdErrors];

export type PatchRoutinesByIdResponses = {
    /**
     * Successful Response
     */
    200: RoutineRead;
};

export type PatchRoutinesByIdResponse = PatchRoutinesByIdResponses[keyof PatchRoutinesByIdResponses];

export type GetExercisesData = {
    body?: never;
    path?: never;
    query?: {
        routine_id?: number | null;
    };
    url: '/exercises/';
};

export type GetExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExercisesError = GetExercisesErrors[keyof GetExercisesErrors];

export type GetExercisesResponses = {
    /**
     * Successful Response
     */
    200: Array<ExerciseRead>;
};

export type GetExercisesResponse = GetExercisesResponses[keyof GetExercisesResponses];

export type PostExercisesData = {
    body: ExerciseCreate;
    path?: never;
    query?: never;
    url: '/exercises/';
};

export type PostExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostExercisesError = PostExercisesErrors[keyof PostExercisesErrors];

export type PostExercisesResponses = {
    /**
     * Successful Response
     */
    201: ExerciseRead;
};

export type PostExercisesResponse = PostExercisesResponses[keyof PostExercisesResponses];

export type GetExercisesByExerciseIdData = {
    body?: never;
    path: {
        exercise_id: number;
    };
    query?: never;
    url: '/exercises/{exercise_id}';
};

export type GetExercisesByExerciseIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExercisesByExerciseIdError = GetExercisesByExerciseIdErrors[keyof GetExercisesByExerciseIdErrors];

export type GetExercisesByExerciseIdResponses = {
    /**
     * Successful Response
     */
    200: ExerciseRead;
};

export type GetExercisesByExerciseIdResponse = GetExercisesByExerciseIdResponses[keyof GetExercisesByExerciseIdResponses];

export type PatchExercisesByExerciseIdData = {
    body: ExerciseUpdate;
    path: {
        exercise_id: number;
    };
    query?: never;
    url: '/exercises/{exercise_id}';
};

export type PatchExercisesByExerciseIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchExercisesByExerciseIdError = PatchExercisesByExerciseIdErrors[keyof PatchExercisesByExerciseIdErrors];

export type PatchExercisesByExerciseIdResponses = {
    /**
     * Successful Response
     */
    200: ExerciseRead;
};

export type PatchExercisesByExerciseIdResponse = PatchExercisesByExerciseIdResponses[keyof PatchExercisesByExerciseIdResponses];

export type GetWorkoutsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workouts/';
};

export type GetWorkoutsResponses = {
    /**
     * Successful Response
     */
    200: Array<WorkoutRead>;
};

export type GetWorkoutsResponse = GetWorkoutsResponses[keyof GetWorkoutsResponses];

export type PostWorkoutsData = {
    body: WorkoutCreate;
    path?: never;
    query?: never;
    url: '/workouts/';
};

export type PostWorkoutsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostWorkoutsError = PostWorkoutsErrors[keyof PostWorkoutsErrors];

export type PostWorkoutsResponses = {
    /**
     * Successful Response
     */
    201: WorkoutRead;
};

export type PostWorkoutsResponse = PostWorkoutsResponses[keyof PostWorkoutsResponses];

export type PatchWorkoutsByWorkoutIdData = {
    body: WorkoutUpdate;
    path: {
        workout_id: number;
    };
    query?: never;
    url: '/workouts/{workout_id}';
};

export type PatchWorkoutsByWorkoutIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchWorkoutsByWorkoutIdError = PatchWorkoutsByWorkoutIdErrors[keyof PatchWorkoutsByWorkoutIdErrors];

export type PatchWorkoutsByWorkoutIdResponses = {
    /**
     * Successful Response
     */
    200: Workout;
};

export type PatchWorkoutsByWorkoutIdResponse = PatchWorkoutsByWorkoutIdResponses[keyof PatchWorkoutsByWorkoutIdResponses];

export type DeleteRoutinesExercisesData = {
    body?: never;
    path?: never;
    query: {
        routine_id: number;
        exercise_id: number;
    };
    url: '/routines-exercises/';
};

export type DeleteRoutinesExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoutinesExercisesError = DeleteRoutinesExercisesErrors[keyof DeleteRoutinesExercisesErrors];

export type DeleteRoutinesExercisesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoutinesExercisesResponse = DeleteRoutinesExercisesResponses[keyof DeleteRoutinesExercisesResponses];

export type PostRoutinesExercisesData = {
    body: RoutineExerciseLink;
    path?: never;
    query?: never;
    url: '/routines-exercises/';
};

export type PostRoutinesExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRoutinesExercisesError = PostRoutinesExercisesErrors[keyof PostRoutinesExercisesErrors];

export type PostRoutinesExercisesResponses = {
    /**
     * Successful Response
     */
    201: RoutineExerciseLink;
};

export type PostRoutinesExercisesResponse = PostRoutinesExercisesResponses[keyof PostRoutinesExercisesResponses];

export type DeleteWorkoutExercisesData = {
    body?: never;
    path?: never;
    query: {
        workout_id: number;
        exercise_id: number;
    };
    url: '/workout-exercises/';
};

export type DeleteWorkoutExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkoutExercisesError = DeleteWorkoutExercisesErrors[keyof DeleteWorkoutExercisesErrors];

export type DeleteWorkoutExercisesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkoutExercisesResponse = DeleteWorkoutExercisesResponses[keyof DeleteWorkoutExercisesResponses];

export type GetWorkoutExercisesData = {
    body?: never;
    path?: never;
    query?: {
        workout_id?: number | null;
        exercise_id?: number | null;
    };
    url: '/workout-exercises/';
};

export type GetWorkoutExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkoutExercisesError = GetWorkoutExercisesErrors[keyof GetWorkoutExercisesErrors];

export type GetWorkoutExercisesResponses = {
    /**
     * Successful Response
     */
    200: Array<WorkoutExerciseLink>;
};

export type GetWorkoutExercisesResponse = GetWorkoutExercisesResponses[keyof GetWorkoutExercisesResponses];

export type PostWorkoutExercisesData = {
    body: WorkoutExerciseLink;
    path?: never;
    query?: never;
    url: '/workout-exercises/';
};

export type PostWorkoutExercisesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostWorkoutExercisesError = PostWorkoutExercisesErrors[keyof PostWorkoutExercisesErrors];

export type PostWorkoutExercisesResponses = {
    /**
     * Successful Response
     */
    201: WorkoutExerciseLink;
};

export type PostWorkoutExercisesResponse = PostWorkoutExercisesResponses[keyof PostWorkoutExercisesResponses];

export type DeletePlansRoutinesData = {
    body?: never;
    path?: never;
    query: {
        plan_id: number;
        routine_id: number;
    };
    url: '/plans-routines/';
};

export type DeletePlansRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePlansRoutinesError = DeletePlansRoutinesErrors[keyof DeletePlansRoutinesErrors];

export type DeletePlansRoutinesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePlansRoutinesResponse = DeletePlansRoutinesResponses[keyof DeletePlansRoutinesResponses];

export type GetPlansRoutinesData = {
    body?: never;
    path?: never;
    query?: {
        plan_id?: number | null;
        routine_id?: number | null;
    };
    url: '/plans-routines/';
};

export type GetPlansRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlansRoutinesError = GetPlansRoutinesErrors[keyof GetPlansRoutinesErrors];

export type GetPlansRoutinesResponses = {
    /**
     * Successful Response
     */
    200: Array<PlanRoutineLink>;
};

export type GetPlansRoutinesResponse = GetPlansRoutinesResponses[keyof GetPlansRoutinesResponses];

export type PostPlansRoutinesData = {
    body: PlanRoutineLink;
    path?: never;
    query?: never;
    url: '/plans-routines/';
};

export type PostPlansRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPlansRoutinesError = PostPlansRoutinesErrors[keyof PostPlansRoutinesErrors];

export type PostPlansRoutinesResponses = {
    /**
     * Successful Response
     */
    201: PlanRoutineLink;
};

export type PostPlansRoutinesResponse = PostPlansRoutinesResponses[keyof PostPlansRoutinesResponses];